server:
  port: 8080
spring:
  application:
    name: demo
  data:
    redis:
      host: localhost
      port: 6379
      password: suragi
      database: 0
      connect-timeout: 3

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: gswh2023fdzm
    druid:
      initial-size: 3
      max-wait: 50
      min-idle: 5
      max-active: 100
      #druid监控
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
      web-stat-filter:
        enabled: true

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.example.demo.dal.domain
  configuration:
    auto-mapping-behavior: full
    cache-enabled: true
    default-fetch-size: 100
    default-statement-timeout: 30
    default-executor-type: simple
    jdbc-type-for-null: other
    lazy-load-trigger-methods: equals,clone,hashCode,toString
    #开启sql打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl